cd ./alg_module_license_plate_recognition/project
sudo ./make_install.sh
cd ../../
cd ./alg_module_helmet_detect_in_region/project
sudo ./make_install.sh
cd ../../
cd ./alg_module_burst_into_ban_detection/project
sudo ./make_install.sh
cd ../../
cd ./alg_module_traffic_flow_detection/project
sudo ./make_install.sh
cd ../../
cd ./alg_module_detect_tracking/project
sudo ./make_install.sh
cd ../../
cd ./alg_module_license_plate_detection/project
sudo ./make_install.sh
cd ../../
